### ISSUE TITLE
Example use asyncapi

### ISSUE THREAD

**Issue by blaggacao** [ThreeDotsLabs/wild-workouts-go-ddd-example#8]
The closing PR of https://github.com/asyncapi/asyncapi/issues/113 implemented:

```yaml
channels:
  user/created:
    subscribe:
      headers:
        application/x-protobuf:
          $ref: 'path/to/user-created.proto#Headers'
      payload:
        application/x-protobuf:
          $ref: 'path/to/user-created.proto#UserCreated'
```
As two valuable learning units, it would be nice to:
-  see wild-workouts-go-ddd-example API consumable through: https://playground.asyncapi.io/
- see watermill meet with https://github.com/asyncapi/generator#how-to-create-a-template

See also:
&rarr; https://github.com/asyncapi/generator/blob/master/docs/authoring.md
&rarr; https://github.com/asyncapi/generator/blob/master/docs/templates-recipes.md
